language: python
python:  
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: ''
    app: ''
    env: ''
    bucket_name: ''
    on:
      all_branches: true