language: python
python:  
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m black . --check
  - flake8 .
  - coverage run --source=hello,polls manage.py test

after_script:
  - python -m coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: 'us-west-2'
    app: 'polls-app'
    env: 'polls-env'
    bucket_name: 'elasticbeanstalk-us-west-2-483486020413'
    on:
      all_branches: true