language: python
python:  
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m black . --check
  - flake8 .
  - coverage run --source=polls manage.py test

after_success:
  - python -m coveralls
  
# deploy:
#   - provider: elasticbeanstalk
#     access_key_id: $ACCESSKEYID
#     secret_access_key: $SECRETACCESSKEY
#     region: ''
#     app: ''
#     env: ''
#     bucket_name: ''
#     on:
#       all_branches: true